### ISSUE TITLE
state: absent may be applied to next element of list

### ISSUE THREAD

**Issue by tkoike880** [link-u/ansible-roles-v2_php7#14]
Hi.
I discovered strange behavior.

I appended `state: absent` as below.
```yaml
php7_fpm_php_ini_file:
  - section: opcache
    key: opcache.preload
    value: /path/to/preload.php
    state: absent  # added this
  - section: opcache
    key: opcache.preload_user
    value: www-data
```

The actual diff is below.
```diff
TASK [php : Remove parameter from fpm/php.ini when state is absent] ****************
...
--- before: /etc/php/8.1/fpm/php.ini (content)
+++ after: /etc/php/8.1/fpm/php.ini (content)
@@ -1904,7 +1904,7 @@
-opcache.preload_user = www-data
+;opcache.preload_user = www-data

changed: [xxxxxxxx] => (item={'section': 'opcache', 'key': 'opcache.preload', 'value': '/path/to/preload.php', 'state': 'absent'})
```

For your information, I use this version of commit SHA: `f057291`.

This might be because of a bug of `combine_dict_list`.
I hope that this behavior will be fixed.
